// config.js - Configuration and data for COCODRILIO website

const config = {
    site: {
        title: "COCODRILIO | Embroidery & Geek Stuff",
        description: "Custom embroidery on clothes, individual designs, and coming soon: 3D printing & retro computer club!",
        established: "2026",
        email: "hello@cocodrilio.com",
        location: "Wroclaw, Poland",
        socials: {
            instagram: "#",
            facebook: "#",
            twitter: "#"
        }
    },

    colors: {
        neon: {
            cyan: '#00e5ff',
            pink: '#ff00ff',
            green: '#00ff88',
            orange: '#ff9500',
            yellow: '#ffff00'
        },
        dark: {
            bg: '#0a0a0f',
            card: '#12121a'
        }
    },

    fonts: {
        primary: ['Inter', 'sans-serif'],
        pixel: ['"Press Start 2P"', 'cursive']
    },

    images: {
        logo: "images/logo.png",
        embroidery: "images/emb.png",
        printing3d: "images/3d.png",
        computerClub: "images/arcade.png"
    },

    services: [
        {
            id: "embroidery",
            title: "Custom Embroidery",
            status: "ACTIVE",
            statusColor: "neon-green",
            description: "High-quality embroidery on clothes, hats, and bags. Send us your pixel art or vector designs, and we'll stitch them with precision.",
            features: ["Custom Logos", "Individual Designs", "Patches & Badges"],
            progress: 100,
            image: "embroidery"
        },
        {
            id: "3d-printing",
            title: "3D Printing",
            status: "COMING SOON",
            statusColor: "neon-yellow",
            description: "Bringing your digital models to life. We are setting up our farm to print figurines, cosplay props, and replacement parts.",
            features: [],
            progress: 45,
            image: "printing3d"
        },
        {
            id: "computer-club",
            title: "Retro Computer Club",
            status: "PLANNED",
            statusColor: "neon-yellow",
            description: "A sanctuary for old-school gaming. CRT monitors, mechanical keyboards, and classic arcade cabinets. Join the LAN party of the future.",
            features: [],
            progress: 0,
            image: "computerClub"
        }
    ],

    stats: [
        { value: "100%", label: "Custom", color: "neon-cyan" },
        { value: "Retro", label: "Vibe", color: "neon-pink" },
        { value: "Future", label: "Tech", color: "neon-green" }
    ],

    translations: {
        en: {
            nav_about: "About",
            nav_services: "Services",
            nav_contact: "Contact Us",
            hero_est: "EST.",
            hero_welcome: "WELCOME TO",
            hero_tag_1: "EMBROIDERY",
            hero_tag_2: "3D PRINTING",
            hero_tag_3: "GEEK STUFF",
            hero_tag_4: "COMPUTER CLUB",
            hero_desc: "Custom embroidery on clothes, individual designs, and coming soon: 3D printing & retro computer club!",
            btn_explore: "EXPLORE SERVICES",
            btn_contact: "GET IN TOUCH",
            about_title_1: "WE ARE",
            about_p1: "Born from a love of retro aesthetics and modern technology, Cocodrilio is a creative hub for geeks, makers, and gamers.",
            about_p2: "We specialize in high-quality custom embroidery, turning your favorite pixel art, logos, and designs into wearable art. We're building a future that includes cutting-edge 3D printing and a nostalgic old-school computer club.",
            stat_custom: "Custom",
            stat_vibe: "Vibe",
            stat_retro: "Retro",
            stat_future: "Future",
            stat_tech: "Tech",
            services_title_1: "OUR",
            services_title_2: "SERVICES",
            services_subtitle: "From thread to plastic to pixels.",
            serv_1_title: "Custom Embroidery",
            status_active: "ACTIVE",
            serv_1_desc: "High-quality embroidery on clothes, hats, and bags. Send us your pixel art or vector designs, and we'll stitch them with precision.",
            serv_1_li1: "Custom Logos",
            serv_1_li2: "Individual Designs",
            serv_1_li3: "Patches & Badges",
            btn_order: "ORDER NOW",
            status_soon: "COMING SOON",
            serv_2_title: "3D Printing",
            serv_2_desc: "Bringing your digital models to life. We are setting up our farm to print figurines, cosplay props, and replacement parts.",
            serv_2_progress: "Lab Setup in Progress...",
            status_planned: "PLANNED",
            serv_3_title: "Retro Computer Club",
            serv_3_desc: "A sanctuary for old-school gaming. CRT monitors, mechanical keyboards, and classic arcade cabinets. Join the LAN party of the future.",
            serv_3_date: "Opening Date TBD",
            contact_title_1: "CONTACT",
            contact_title_2: "US",
            contact_subtitle: "Ready to start your project? Drop us a line.",
            form_name: "Name",
            form_email: "Email",
            form_service: "Service Interest",
            form_message: "Message",
            opt_embroidery: "Custom Embroidery",
            opt_3d: "3D Printing (Waitlist)",
            opt_club: "Computer Club (Waitlist)",
            opt_other: "Other",
            btn_send: "SEND MESSAGE",
            footer_email: "Email",
            footer_location: "Location",
            footer_socials: "Socials",
            footer_rights: "ALL RIGHTS RESERVED.",
            footer_made: "Made with",
            footer_and: "and"
        },
        pl: {
            nav_about: "O nas",
            nav_services: "Usługi",
            nav_contact: "Kontakt",
            hero_est: "EST.",
            hero_welcome: "WITAMY W",
            hero_tag_1: "HAFCIE",
            hero_tag_2: "DRUKU 3D",
            hero_tag_3: "GEEK STUFF",
            hero_tag_4: "KLUBIE PC",
            hero_desc: "Indywidualne hafty na ubraniach, własne projekty, a wkrótce: druk 3D i retro klub komputerowy!",
            btn_explore: "ZOBACZ USŁUGI",
            btn_contact: "SKONTAKTUJ SIĘ",
            about_title_1: "JESTEŚMY",
            about_p1: "Narodzeni z miłości do retro estetyki i nowoczesnych technologii, Cocodrilio to kreatywne miejsce dla geeków, majsterkowiczów i graczy.",
            about_p2: "Specjalizujemy się w wysokiej jakości haftach na zamówienie, zamieniając Twoje ulubione pixel arty, logotypy i projekty w noszalną sztukę. Budujemy przyszłość, która obejmuje najnowocześniejszy druk 3D i nostalgiczną starą szkołę klubu komputerowego.",
            stat_custom: "Na Miarę",
            stat_vibe: "Klimat",
            stat_retro: "Retro",
            stat_future: "Przyszłość",
            stat_tech: "Technologia",
            services_title_1: "NASZE",
            services_title_2: "USŁUGI",
            services_subtitle: "Od nici, przez plastik, po piksele.",
            serv_1_title: "Haft na Zamówienie",
            status_active: "AKTYWNE",
            serv_1_desc: "Wysokiej jakości hafty na ubraniach, czapkach i torbach. Wyślij nam swoje pixel arty lub projekty wektorowe, a my je precyzyjnie wyszyjemy.",
            serv_1_li1: "Własne Logotypy",
            serv_1_li2: "Indywidualne Projekty",
            serv_1_li3: "Naszywki i Odznaki",
            btn_order: "ZAMÓW TERAZ",
            status_soon: "WKRÓTCE",
            serv_2_title: "Druk 3D",
            serv_2_desc: "Ożywiamy Twoje modele cyfrowe. Konfigurujemy naszą farmę do druku figurek, rekwizytów cosplay i części zamiennych.",
            serv_2_progress: "Trwa konfiguracja laboratorium...",
            status_planned: "PLANOWANE",
            serv_3_title: "Retro Klub Komputerowy",
            serv_3_desc: "Sanktuarium dla gier starej szkoły. Monitory CRT, mechaniczne klawiatury i klasyczne automaty arcade. Dołącz do LAN party przyszłości.",
            serv_3_date: "Data otwarcia TBD",
            contact_title_1: "KONTAKT",
            contact_title_2: "Z NAMI",
            contact_subtitle: "Gotowy, aby zacząć swój projekt? Napisz do nas.",
            form_name: "Imię",
            form_email: "Email",
            form_service: "Zainteresowanie",
            form_message: "Wiadomość",
            opt_embroidery: "Haft na Zamówienie",
            opt_3d: "Druk 3D (Lista oczekujących)",
            opt_club: "Klub Komputerowy (Lista oczekujących)",
            opt_other: "Inne",
            btn_send: "WYŚLIJ WIADOMOŚĆ",
            footer_email: "Email",
            footer_location: "Lokalizacja",
            footer_socials: "Social Media",
            footer_rights: "WSZELKIE PRAWA ZASTRZEŻONE.",
            footer_made: "Stworzone z",
            footer_and: "i"
        },
        ua: {
            nav_about: "Про нас",
            nav_services: "Послуги",
            nav_contact: "Контакти",
            hero_est: "ЗАСН.",
            hero_welcome: "ЛАСКАВО ПРОСИМО ДО",
            hero_tag_1: "ВИШИВКА",
            hero_tag_2: "3Д ДРУК",
            hero_tag_3: "ҐІК СТАФФ",
            hero_tag_4: "КОМП'ЮТЕРНИЙ КЛУБ",
            hero_desc: "Індивідуальна вишивка на одязі, власні дизайни, а незабаром: 3D друк та ретро комп'ютерний клуб!",
            btn_explore: "ДИВИТИСЬ ПОСЛУГИ",
            btn_contact: "ЗВ'ЯЗАТИСЬ",
            about_title_1: "МИ",
            about_p1: "Народжені з любові до ретро естетики та сучасних технологій, Cocodrilio є творчим простором для ґіків, майстрів та геймерів.",
            about_p2: "Ми спеціалізуємось на високоякісній індивідуальній вишивці, перетворюючи ваші улюблені піксель-арти, логотипи та дизайни на носбельне мистецтво. Ми будуємо майбутнє, що включає передовий 3D друк та ностальгічний старий добрий комп'ютерний клуб.",
            stat_custom: "Індивід.",
            stat_vibe: "Вайб",
            stat_retro: "Ретро",
            stat_future: "Майбутнє",
            stat_tech: "Техно",
            services_title_1: "НАШІ",
            services_title_2: "ПОСЛУГИ",
            services_subtitle: "Від нитки до пластику та пікселів.",
            serv_1_title: "Індивідуальна Вишивка",
            status_active: "АКТИВНО",
            serv_1_desc: "Високоякісна вишивка на одязі, капелюхах та сумках. Надішліть нам свої піксель-арти або векторні дизайни, і ми вишиємо їх з точністю.",
            serv_1_li1: "Власні Логотипи",
            serv_1_li2: "Індивідуальні Дизайни",
            serv_1_li3: "Нашивки та Значки",
            btn_order: "ЗАМОВИТИ",
            status_soon: "НЕЗАБАРОМ",
            serv_2_title: "3D Друк",
            serv_2_desc: "Оживлюємо ваші цифрові моделі. Ми налаштовуємо нашу ферму для друку фігурок, реквізиту для косплею та запчастин.",
            serv_2_progress: "Налаштування лабораторії...",
            status_planned: "ПЛАНУЄТЬСЯ",
            serv_3_title: "Ретро Комп'ютерний Клуб",
            serv_3_desc: "Святилище для старих ігор. ЕЛТ монітори, механічні клавіатури та класичні аркадні автомати. Приєднуйтесь до LAN вечірки майбутнього.",
            serv_3_date: "Дата відкриття TBD",
            contact_title_1: "ЗВ'ЯЖІТЬСЯ",
            contact_title_2: "З НАМИ",
            contact_subtitle: "Готові розпочати свій проект? Напишіть нам.",
            form_name: "Ім'я",
            form_email: "Email",
            form_service: "Інтерес",
            form_message: "Повідомлення",
            opt_embroidery: "Індивідуальна Вишивка",
            opt_3d: "3D Друк (Лист очікування)",
            opt_club: "Комп'ютерний Клуб (Лист очікування)",
            opt_other: "Інше",
            btn_send: "ВІДПРАВИТИ",
            footer_email: "Email",
            footer_location: "Локація",
            footer_socials: "Соцмережі",
            footer_rights: "ВСІ ПРАВА ЗАХИЩЕНІ.",
            footer_made: "Зроблено з",
            footer_and: "та"
        }
    }
};

// Make config available globally
window.config = config;